(function(g){var window=this;'use strict';var Xhb=function(a){g.V.call(this,{I:"div",S:"ytp-inline-preview-ui"});this.hg=!1;this.player=a;this.T(a,"onStateChange",this.DP);this.T(a,"videodatachange",this.Aw);this.T(a,"onInlinePreviewModeChange",this.w4);this.sf=new g.Qp(this.Lv,null,this);g.J(this,this.sf)},y6=function(a){g.uT.call(this,a);
this.j=new Xhb(this.player);g.J(this,this.j);this.j.hide();g.qS(this.player,this.j.element,4);a.isInline()&&(this.load(),a=a.getRootNode(),g.aq(a,["ytp-inline-preview-mode","ytp-no-contextmenu"]))};
g.x(Xhb,g.V);g.k=Xhb.prototype;
g.k.CM=function(){this.tooltip=new g.RV(this.player,this);g.J(this,this.tooltip);g.qS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Rc=new g.XT(this.player);g.J(this,this.Rc);this.Vj=new g.V({I:"div",Ka:["ytp-inline-preview-scrim"]});g.J(this,this.Vj);this.Vj.Ha(this.element);this.T(this.Vj.element,"click",this.gH);this.tj=new g.KV(this.player,this,300);g.J(this,this.tj);this.tj.Ha(this.Vj.element);this.controls=new g.V({I:"div",S:"ytp-inline-preview-controls"});g.J(this,this.controls);
this.controls.Ha(this.element);var a=new g.aV(this.player,this,this.player.W().N("kevlar_simp_remove_min_width_for_mute_button"));g.J(this,a);a.Ha(this.controls.element);a=new g.IV(this.player,this);g.J(this,a);a.Ha(this.controls.element);this.Kc=new g.hV(this.player,this);g.J(this,this.Kc);g.qS(this.player,this.Kc.element,4);this.T(this.player,"appresize",this.Hb);this.T(this.player,"fullscreentoggled",this.Hb);this.Hb()};
g.k.show=function(){g.Rp(this.sf);this.hg||(this.CM(),this.hg=!0);0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.Kc.show();this.player.Pa("onInlinePreviewUiReady")};
g.k.hide=function(){this.sf.stop();g.V.prototype.hide.call(this);this.player.isInline()||this.hg&&this.Kc.hide()};
g.k.ra=function(){g.V.prototype.ra.call(this)};
g.k.gH=function(a){a.target===this.Vj.element&&this.player.Pa("onExpandInlinePreview",a)};
g.k.w4=function(){g.dq(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Te=function(){this.Kc.zc();this.tj.zc()};
g.k.Lv=function(){this.Te();g.Rp(this.sf)};
g.k.Hb=function(){g.tV(this.Kc,0,this.player.kb().getPlayerSize().width,!1);g.iV(this.Kc)};
g.k.DP=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.Aw=function(a,b){if(this.player.isInline()){g.dq(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.YI);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.dq(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Ec=function(){return this.tooltip};
g.k.Bg=function(){return!1};
g.k.ah=function(){return!1};
g.k.Yb=function(){return!1};
g.k.Wl=function(){return!1};
g.k.bI=function(){};
g.k.Sp=function(){};
g.k.uy=function(){};
g.k.Rm=function(){return null};
g.k.NF=function(){return null};
g.k.TL=function(){return new g.xe(0,0)};
g.k.Bk=function(){return new g.Zm(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Wv=function(a,b,c,d,e){var f=d=0,h=0,l=g.nn(a);if(b){c=g.Zp(b,"ytp-mute-button");var m=g.Zp(b,"ytp-subtitles-button"),n=g.ln(b,this.element);b=g.nn(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.kb().getPlayerSize().width;h=g.pe(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.xp=function(){};
g.k.Nl=function(){return!1};
g.k.UD=function(){};
g.k.Sz=function(){};
g.k.jr=function(){};
g.k.ir=function(){};
g.k.WA=function(){};
g.k.ws=function(){};
g.k.FD=function(){};g.x(y6,g.uT);y6.prototype.Zk=function(){return!1};
y6.prototype.load=function(){this.player.hideControls();this.j.show()};
y6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.tT("inline_preview",y6);})(_yt_player);
